Improve testing in Travis CI. Use Symfony's PHPUnit bridge.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,20 +1,62 @@
 language: php
-php:
-  - 7.1
-  - 7.2
-  - hhvm
-  - nightly
+sudo: false
+cache:
+    directories:
+        - $HOME/.composer/cache/files
+
+env:
+    global:
+        - PHPUNIT_FLAGS="-v"
+        - SYMFONY_DEPRECATIONS_HELPER="max[self]=0"
 
 matrix:
+    fast_finish: true
+    include:
+          # Minimum supported dependencies with the latest and oldest PHP version
+        - php: 7.3
+          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
+        - php: 7.0
+          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
+
+          # Test the latest stable release
+        - php: 7.0
+        - php: 7.1
+        - php: 7.2
+        - php: 7.3
+          env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text --coverage-clover=coverage.clover"
+
+          # Test with Symfony 3
+        - php: 7.3
+          env: DEPENDENCIES="symfony/lts:^3"
+
+          # Latest commit to master
+        - php: 7.3
+          env: STABILITY="dev"
+
+          # Upcoming PHP version
+        - php: 7.4snapshot
+
     allow_failures:
-        - php: hhvm
+          # dev-master is allowed to fail
+        - env: STABILITY="dev"
+          # Upcoming PHP version is allowed to fail
+        - php: 7.4snapshot
 
-before_script:
-  - curl -s http://getcomposer.org/installer | php
-  - php composer.phar install
+before_install:
+    - if [ "$COVERAGE" != true ]; then phpenv config-rm xdebug.ini || true; fi
+    - if [ -n "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
+    - if [ -n "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;
 
-script: phpunit --coverage-clover=coverage.clover
+install:
+    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
+
+script:
+    - composer validate --strict --no-check-lock
+    - ./vendor/bin/phpunit ${PHPUNIT_FLAGS}
 
 after_script:
-  - wget https://scrutinizer-ci.com/ocular.phar
-  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
+  - |
+    if [ "$COVERAGE" = true ] && [ -e coverage.clover ]; then
+      wget https://scrutinizer-ci.com/ocular.phar
+      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
+    fi
